#cloud-config
package_upgrade: true
packages:
  - nginx
  - git
runcmd:
  # install Node.js
  - 'curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -'
  - 'sudo apt-get install -y nodejs'
  # clone GitHub Repo into myapp directory
  - 'cd /home/azureuser'
  - git clone "https://github.com/Azure-Samples/js-e2e-vm" myapp
  # Start app
  - 'cd myapp && npm install && npm start'
  # restart NGINX
  - systemctl restart nginx

# az vmss create -g 2-april-22 -n MyVmss --image debian --custom-data init.yml

runcmd:
- systemctl enable nginx.service
- git clone "https://github.com/Ananyojha/ananyojha.github.io.git" 
- 'cp -r ./ananyojha.github.io/* /var/www/html/'
- systemctl restart nginx

#ssl

runcmd:
  - export DOMAIN=ananayojha.rocks
  - export SUBDOMAIN=demo
  - export EMAIL=mail@gmail.com
  - add-apt-repository ppa:certbot/certbot -y
  - apt-get update
  - apt install python-certbot-nginx -y
  # add domain name to nginx config, restart it
  - sed -i 's/server_name _;/server_name '$SUBDOMAIN"."$DOMAIN';/' /etc/nginx/sites-available/default
  - systemctl restart nginx
  - certbot --nginx -n -d $DROPLET_NAME"."$DOMAIN --email $EMAIL --agree-tos --redirect --hsts
  - systemctl reboot
# add renewal cron
write_files:
  - owner: root:root
    path: /etc/cron.d/letsencrypt_renew
    content: "15 3 * * * /usr/bin/certbot renew --quiet"
